theme: jekyll-theme-architect
title: ThePitz.io
exclude: [vendor]
plugins:
  - jekyll-seo-tag
# Google Analytics
google_analytics: UA-126616292-1

url: https://thepitz.io/
author: Noam Castel

twitter:
  username: pitz_the
  card: summary

social:
  name: Noam Castel
  links:
        - https://twitter.com/noamoss
        - https://www.linkedin.com/in/noam-castel-036976b
        - https://github.com/noamoss
