theme: jekyll-theme-architect
title: ThePitz.studio
exclude: [vendor]

plugins:
  - jekyll-seo-tag
# Google Analytics
google_analytics: UA-126616292-1

url: https://about.thepitz.studio/
baseurl: ''
author: Noam Castel

social:
  name: Noam Castel
  links:
        - https://www.linkedin.com/in/noam-castel-036976b
        - https://github.com/noamoss
